/**
 * Reading, courses, portfolio and writing.
 *
 * The six books flagged `isCoreInterviewResource` are the exact list from
 * `current_analysis.txt` Part 7. The seven portfolio projects are Part 5, in the
 * audit's own ROI order.
 */

import { SKILL_IDS as S } from './skills.mjs'
import { PROGRAMME_START, addDays, addMonths, id, monthEnd } from './util.mjs'

/* ------------------------------------------------------------- reading --- */

const BOOKS = [
  {
    title: 'Decode and Conquer',
    author: 'Lewis C. Lin',
    hours: 10,
    skills: ['Product Sense', 'Communication'],
    core: true,
    priority: 'high',
    status: 'wishlist',
    pages: 320,
    why: 'The interview-answer frameworks. CIRCLES, AARM, DIGS. Read it for structure, not for insight.',
  },
  {
    title: 'Cracking the PM Interview',
    author: 'Gayle Laakmann McDowell & Jackie Bavaro',
    hours: 12,
    skills: ['Product Sense', 'Communication', 'Metrics'],
    core: true,
    priority: 'high',
    status: 'wishlist',
    pages: 368,
    why: 'Breadth across every round type, plus a realistic view of how loops are actually scored.',
  },
  {
    title: 'Inspired',
    author: 'Marty Cagan',
    hours: 11,
    skills: ['Product Discovery', 'Product Strategy', 'Leadership'],
    core: true,
    priority: 'high',
    status: 'reading',
    pages: 368,
    progress: 42,
    why: 'The canonical description of how strong product organisations work. Read it to calibrate your own vocabulary against the industry standard.',
    takeaways: [
      'Empowered teams are given problems, not features — this is the altitude the audit says top companies expect',
      'Product discovery and delivery are separate activities with different risk profiles',
      'The roadmap is a list of hypotheses, not a list of commitments',
    ],
  },
  {
    title: 'Escaping the Build Trap',
    author: 'Melissa Perri',
    hours: 8,
    skills: ['Product Strategy', 'Metrics', 'Business Thinking'],
    core: true,
    priority: 'high',
    status: 'wishlist',
    pages: 200,
    why: 'Directly addresses the Product Strategy gap: moving from "how should this evolve" to "should we build this at all".',
  },
  {
    title: 'Continuous Discovery Habits',
    author: 'Teresa Torres',
    hours: 9,
    skills: ['Product Discovery', 'Product Sense'],
    core: true,
    priority: 'high',
    status: 'wishlist',
    pages: 328,
    why: 'The opportunity solution tree and interview cadence — the two specific things the audit says your discovery evidence lacks.',
  },
  {
    title: 'Lean Analytics',
    author: 'Alistair Croll & Benjamin Yoskovitz',
    hours: 10,
    skills: ['Analytics', 'Metrics', 'Business Thinking'],
    core: true,
    priority: 'critical',
    status: 'reading',
    pages: 440,
    progress: 18,
    why: 'One metric that matters, stage-appropriate metrics, and the business-model archetypes. Read alongside Month 1.',
    takeaways: ['Pick the One Metric That Matters for the current stage and ignore the rest'],
  },
  {
    title: 'Trustworthy Online Controlled Experiments',
    author: 'Kohavi, Tang & Xu',
    hours: 20,
    skills: ['Experimentation', 'Analytics'],
    core: false,
    priority: 'critical',
    status: 'wishlist',
    pages: 274,
    why: 'The definitive experimentation text. Parts I and II are the Month 3 curriculum.',
  },
  {
    title: 'Designing Data-Intensive Applications',
    author: 'Martin Kleppmann',
    hours: 28,
    skills: ['Technical Depth', 'Systems Thinking'],
    core: false,
    priority: 'high',
    status: 'wishlist',
    pages: 616,
    why: 'Chapters 1–6 close most of the named technical-depth gap: data models, storage, replication, partitioning.',
  },
  {
    title: 'Hooked',
    author: 'Nir Eyal',
    hours: 6,
    skills: ['Product Sense'],
    core: false,
    priority: 'medium',
    status: 'wishlist',
    pages: 256,
    why: 'The consumer-behaviour vocabulary the audit says is missing. Read it critically, not devotionally.',
  },
  {
    title: 'Monetizing Innovation',
    author: 'Madhavan Ramanujam & Georg Tacke',
    hours: 8,
    skills: ['Business Thinking', 'Product Strategy'],
    core: false,
    priority: 'medium',
    status: 'wishlist',
    pages: 256,
    why: 'Pricing before you build. Feeds the Month 9 pricing analyses directly.',
  },
  {
    title: 'The Cold Start Problem',
    author: 'Andrew Chen',
    hours: 9,
    skills: ['Product Strategy', 'Business Thinking'],
    core: false,
    priority: 'medium',
    status: 'wishlist',
    pages: 368,
    why: 'Network effects and marketplace dynamics — both on the should-improve list.',
  },
  {
    title: 'Good Strategy, Bad Strategy',
    author: 'Richard Rumelt',
    hours: 11,
    skills: ['Product Strategy'],
    core: false,
    priority: 'high',
    status: 'wishlist',
    pages: 336,
    why: 'Teaches you to recognise strategy that is actually just a goal with adjectives. Sharpens the strategy memo.',
  },
  {
    title: 'Thinking in Systems',
    author: 'Donella Meadows',
    hours: 7,
    skills: ['Systems Thinking'],
    core: false,
    priority: 'low',
    status: 'reference',
    pages: 240,
    why: 'You already think this way. Read it to acquire the shared vocabulary so you can name what you do.',
  },
  {
    title: 'Storytelling with Data',
    author: 'Cole Nussbaumer Knaflic',
    hours: 6,
    skills: ['Communication', 'Analytics'],
    core: false,
    priority: 'medium',
    status: 'wishlist',
    pages: 288,
    why: 'Executive storytelling is the named communication gap, and most of it is about what you remove.',
  },
]

const ARTICLES = [
  {
    title: 'The Metrics Trap',
    author: 'Reforge',
    kind: 'article',
    hours: 1,
    skills: ['Metrics'],
    status: 'finished',
    progress: 100,
    rating: 4,
    priority: 'medium',
    why: 'Why input metrics beat output metrics for team direction.',
    takeaways: ['Teams move input metrics; leadership tracks output metrics'],
  },
  {
    title: 'How to Measure Anything in Product',
    author: 'Lenny\'s Newsletter',
    kind: 'article',
    hours: 1,
    skills: ['Metrics', 'Analytics'],
    status: 'finished',
    progress: 100,
    rating: 5,
    priority: 'medium',
    why: 'Practical approach to instrumenting things that feel unmeasurable.',
    takeaways: ['Anything can be measured badly, and badly is usually enough to decide'],
  },
  {
    title: 'Overlapping Experiments Infrastructure',
    author: 'Google (Tang et al.)',
    kind: 'paper',
    hours: 3,
    skills: ['Experimentation', 'Technical Depth'],
    status: 'wishlist',
    progress: 0,
    priority: 'high',
    why: 'How Google actually runs thousands of concurrent experiments. Read it before any experimentation interview.',
  },
  {
    title: 'Kohavi: Seven Rules of Thumb for Web Site Experimenters',
    author: 'Kohavi et al.',
    kind: 'paper',
    hours: 2,
    skills: ['Experimentation'],
    status: 'wishlist',
    progress: 0,
    priority: 'high',
    why: 'Concrete, empirical rules. The kind of specificity that separates practitioners from readers.',
  },
  {
    title: 'The Rise of the Product Engineer',
    author: 'Various',
    kind: 'blog-post',
    hours: 1,
    skills: ['Technical Depth'],
    status: 'wishlist',
    progress: 0,
    priority: 'low',
    why: 'Context on how technical expectations for PMs are shifting.',
  },
]

export function buildBooks() {
  const all = [...BOOKS.map((b) => ({ ...b, kind: 'book' })), ...ARTICLES]

  return all.map((item, index) => {
    const progress = item.progress ?? (item.status === 'finished' ? 100 : 0)
    const isFinished = item.status === 'finished'
    const isReading = item.status === 'reading'

    return {
      id: id('bk', item.title),
      title: item.title,
      author: item.author,
      kind: item.kind,
      status: item.status,
      progress,
      pagesTotal: item.pages,
      pagesRead: item.pages ? Math.round((item.pages * progress) / 100) : undefined,
      rating: item.rating,
      estimatedHours: item.hours,
      actualHours: isFinished
        ? item.hours
        : isReading
          ? Math.round(item.hours * (progress / 100) * 10) / 10
          : 0,
      keyTakeaways: item.takeaways ?? [],
      highlights: [],
      // The `why` is the contextual help shown in the UI, and the reason this
      // book is on the list at all rather than any other book.
      notes: item.why,
      skillIds: item.skills.map((n) => S[n]).filter(Boolean),
      startedAt: isFinished || isReading ? addDays(PROGRAMME_START, 3) : undefined,
      completedAt: isFinished ? addDays(PROGRAMME_START, 12) : undefined,
      isCoreInterviewResource: Boolean(item.core),
      priority: item.priority,
      xp: Math.round(item.hours * 12),
      order: index,
    }
  })
}

/* ------------------------------------------------------------- courses --- */

const COURSES = [
  {
    title: 'Mode Analytics SQL Tutorial',
    provider: 'Mode',
    hours: 12,
    difficulty: 3,
    importance: 'critical',
    roi: 10,
    skills: ['Analytics'],
    status: 'in-progress',
    hoursDone: 7,
    cert: false,
    url: 'https://mode.com/sql-tutorial/',
    projects: ['Rebuild the retention query from scratch', 'Window-function drill set'],
    notes: 'The advanced module (window functions) is the part that shows up in interviews. Do it twice.',
  },
  {
    title: 'SQLBolt',
    provider: 'SQLBolt',
    hours: 6,
    difficulty: 2,
    importance: 'critical',
    roi: 9,
    skills: ['Analytics'],
    status: 'done',
    hoursDone: 6,
    cert: false,
    url: 'https://sqlbolt.com',
    projects: ['All 18 lessons completed without hints'],
    notes: 'Fastest possible on-ramp. Finished in week one — the right first move.',
  },
  {
    title: 'Amplitude Academy — Product Analytics',
    provider: 'Amplitude',
    hours: 10,
    difficulty: 2,
    importance: 'critical',
    roi: 9,
    skills: ['Analytics', 'Metrics'],
    status: 'not-started',
    hoursDone: 0,
    cert: true,
    url: 'https://academy.amplitude.com',
    projects: ['Funnel, retention and cohort analyses on a public dataset'],
    notes: 'Month 2. The certificate is worth little; the tool fluency is worth a great deal.',
  },
  {
    title: 'Mixpanel Product Analytics Certification',
    provider: 'Mixpanel',
    hours: 8,
    difficulty: 2,
    importance: 'high',
    roi: 7,
    skills: ['Analytics'],
    status: 'not-started',
    hoursDone: 0,
    cert: true,
    url: 'https://mixpanel.com/blog/product-analytics-certification/',
    projects: ['Rebuild the Amplitude analyses in Mixpanel and compare'],
    notes: 'Second tool, deliberately. Knowing where two tools disagree is the interesting part.',
  },
  {
    title: 'Experimentation for Product Managers',
    provider: 'Reforge / Statsig course',
    hours: 16,
    difficulty: 4,
    importance: 'critical',
    roi: 9,
    skills: ['Experimentation', 'Metrics'],
    status: 'not-started',
    hoursDone: 0,
    cert: true,
    projects: ['Ten A/B test plans', 'One real experiment shipped and analysed'],
    notes: 'Month 3. Pair with Kohavi — the course gives the workflow, the book gives the statistics.',
  },
  {
    title: 'Google Data Analytics Professional Certificate',
    provider: 'Coursera / Google',
    hours: 120,
    difficulty: 3,
    importance: 'medium',
    roi: 4,
    skills: ['Analytics'],
    status: 'not-started',
    hoursDone: 0,
    cert: true,
    url: 'https://www.coursera.org/professional-certificates/google-data-analytics',
    projects: ['Capstone analysis'],
    notes:
      'Low ROI per hour, and the audit explicitly warns against collecting certificates without demonstrable application. Only worth it if you convert every module into a public artefact. Deprioritised on purpose.',
  },
  {
    title: 'Building LLM Applications',
    provider: 'DeepLearning.AI',
    hours: 14,
    difficulty: 4,
    importance: 'high',
    roi: 8,
    skills: ['AI Product Knowledge', 'Technical Depth'],
    status: 'not-started',
    hoursDone: 0,
    cert: true,
    url: 'https://www.deeplearning.ai',
    projects: ['The Month 5 AI prototype'],
    notes: 'Month 5. Focus on the evaluation and retrieval modules; skip the framework-specific parts.',
  },
  {
    title: 'System Design for Product Managers',
    provider: 'Educative',
    hours: 18,
    difficulty: 4,
    importance: 'high',
    roi: 7,
    skills: ['Technical Depth', 'Systems Thinking'],
    status: 'not-started',
    hoursDone: 0,
    cert: false,
    projects: ['Two architecture-focused product documents'],
    notes: 'Month 8. Read alongside DDIA chapters 1–6.',
  },
  {
    title: 'Financial Modeling for SaaS',
    provider: 'Wall Street Prep / equivalent',
    hours: 12,
    difficulty: 4,
    importance: 'medium',
    roi: 6,
    skills: ['Business Thinking'],
    status: 'not-started',
    hoursDone: 0,
    cert: false,
    projects: ['One working SaaS model: MRR, churn, CAC, LTV, payback'],
    notes: 'Month 9. Build the model as you go; a course without the spreadsheet is wasted.',
  },
  {
    title: 'Reforge — Product Strategy',
    provider: 'Reforge',
    hours: 20,
    difficulty: 4,
    importance: 'high',
    roi: 7,
    skills: ['Product Strategy', 'Business Thinking'],
    status: 'not-started',
    hoursDone: 0,
    cert: false,
    projects: ['The strategy memo'],
    notes: 'Expensive. Worth it only if you produce the memo alongside it.',
  },
]

export function buildCourses() {
  return COURSES.map((c, index) => {
    const progress = c.hours > 0 ? Math.round((c.hoursDone / c.hours) * 100) : 0
    return {
      id: id('cs', c.title),
      title: c.title,
      provider: c.provider,
      url: c.url,
      status: c.status,
      hours: c.hours,
      hoursCompleted: c.hoursDone,
      progress,
      difficulty: c.difficulty,
      importance: c.importance,
      roi: c.roi,
      hasCertificate: c.cert,
      certificateUrl: undefined,
      projects: c.projects,
      notes: c.notes,
      skillIds: c.skills.map((n) => S[n]).filter(Boolean),
      startedAt: c.hoursDone > 0 ? addDays(PROGRAMME_START, 2) : undefined,
      completedAt: c.status === 'done' ? addDays(PROGRAMME_START, 8) : undefined,
      xp: Math.round(c.hours * 10 + c.roi * 20),
      order: index,
    }
  })
}

/* ----------------------------------------------------------- portfolio --- */

/**
 * Part 5, in the audit's stated ROI order. `targetMonth` aligns each project
 * with the month of the roadmap that produces it, so the Portfolio page and the
 * Learning Path never disagree about when something is due.
 */
const PROJECTS = [
  {
    title: 'Complete Redesign of a Complex SaaS Workflow',
    kind: 'redesign',
    rank: 1,
    targetMonth: 6,
    hours: 40,
    skills: ['UX', 'Systems Thinking', 'Product Execution'],
    problem:
      'A multi-step operational workflow — approvals, permissions, offline states — has accumulated a decade of exceptions. Users route around it, and support absorbs the difference.',
    goal:
      'Redesign the workflow so the common path is obvious and the exceptional paths remain possible, and show the reasoning at every step.',
    process:
      'Current-state audit → user evidence → information architecture → state machine → permissions model → edge cases → high-fidelity core path.',
    research: 'Support ticket taxonomy, session recordings, five user interviews, and a task-completion baseline.',
    discovery: 'Where users abandon, where they invent workarounds, and which exceptions are actually the same exception.',
    ux: 'IA restructure, a single canonical state machine, progressive disclosure for the exceptional cases, and error states designed rather than defaulted.',
    metrics: 'Task completion rate, time-to-complete, support tickets per 100 workflows, and error rate as a guardrail.',
    tradeoffs:
      'Chose a single opinionated path over configurability. Costs flexibility for the 5% of customers with genuinely unusual processes; buys clarity for the 95%.',
    risks: 'Migration for existing customers; the 5% may be commercially significant. Mitigation is an explicit escape hatch, not configurability everywhere.',
    impact: 'Modelled: 30% reduction in workflow-related support volume, 20% faster task completion.',
    lessons: '',
    why: 'Ranked #1 by the audit because it shows systems thinking, UX and execution simultaneously — all three of your strongest areas, in one public artefact.',
  },
  {
    title: 'AI Copilot PRD',
    kind: 'ai-project',
    rank: 2,
    targetMonth: 5,
    hours: 45,
    skills: ['AI Product Knowledge', 'Technical Depth', 'Metrics'],
    problem:
      'Users need answers that live across documentation, historical records and their own data. Search returns links; they need conclusions.',
    goal:
      'Specify and prototype a copilot that answers grounded questions, shows its sources, and can be evaluated rather than admired.',
    process:
      'Problem framing → retrieval design → prompt architecture → evaluation harness → staged rollout → unit economics.',
    research: 'Query log analysis, ten user interviews, and a taxonomy of question types.',
    discovery: 'Which questions users actually ask, and which of those the system should refuse to answer.',
    ux: 'Streaming responses, visible sources, explicit uncertainty, and a correction path when the answer is wrong.',
    metrics:
      'Groundedness score on a 50-case eval set, answer acceptance rate, cost per query, p95 latency, and escalation rate as a guardrail.',
    tradeoffs:
      'Chose smaller retrieved context with higher precision over large context with higher recall. Costs some coverage; buys trust, latency and margin.',
    risks: 'Hallucination on adversarial queries; cost blow-up at scale. Mitigated by the eval set and a hard context budget.',
    impact: 'Modelled: 40% deflection of a support category, 15 minutes saved per affected user per week.',
    lessons: '',
    why: 'Ranked #2. Covers retrieval, prompts, evaluation, rollout and metrics — and AI product evaluation is on the should-improve list.',
  },
  {
    title: 'Marketplace Strategy Document',
    kind: 'strategy-doc',
    rank: 3,
    targetMonth: 13,
    hours: 30,
    skills: ['Product Strategy', 'Business Thinking'],
    problem: 'A two-sided marketplace has healthy demand and constrained supply, and every growth lever it pulls makes the imbalance worse.',
    goal: 'Produce a strategy that identifies the real constraint and sequences the interventions that relieve it.',
    process: 'Market structure → liquidity analysis → constraint identification → intervention sequencing → risk register.',
    research: 'Public data, competitor structure, and unit economics reconstruction from the outside.',
    discovery: 'Which side is genuinely constrained, and whether the constraint is supply volume or supply quality.',
    ux: 'Not the primary lens — this artefact is deliberately strategic rather than design-led.',
    metrics: 'Liquidity rate, time-to-match, take rate, and supply-side retention as the guardrail.',
    tradeoffs: 'Subsidising supply buys liquidity and costs margin. The document states the price of each option rather than pretending there is a free one.',
    risks: 'Subsidy becomes structural; quality degrades as volume grows.',
    impact: 'Strategic recommendation with sized outcomes and explicit kill criteria.',
    lessons: '',
    why: 'Ranked #3. Deliberately outside B2B operations — it demonstrates strategic thinking beyond your current domain, which is exactly the Product Strategy gap.',
  },
  {
    title: 'Public Product Teardown Series',
    kind: 'teardown',
    rank: 4,
    targetMonth: 10,
    hours: 36,
    skills: ['Product Sense', 'UX', 'Systems Thinking'],
    problem: 'Your product judgement is invisible to anyone who has not worked with you.',
    goal: 'A recurring series analysing Slack, Notion, Linear, Figma and Stripe Dashboard — reconstructing the decisions from the outside.',
    process: 'Fixed format per teardown: the constraint the product chose, the data model implied by the UI, and one thing you would change.',
    research: 'Hands-on use, changelog archaeology, and public engineering writing.',
    discovery: 'What the product refuses to do, and what that refusal buys.',
    ux: 'IA and interaction analysis with annotated screens.',
    metrics: 'Series-level: reach, inbound conversations, and citations by other PMs.',
    tradeoffs: 'A series is a standing commitment. Cadence beats depth; a monthly teardown that ships outranks a perfect one that does not.',
    risks: 'Quality drift as novelty fades. Mitigated by the fixed format and a length ceiling.',
    impact: 'Distribution and discoverability — the direct fix for "outside your network, almost nobody knows you".',
    lessons: '',
    why: 'Ranked #4. Names Slack, Notion, Linear, Figma and Stripe Dashboard specifically. A series compounds where single artefacts do not.',
  },
  {
    title: 'Analytics Case Study — Funnel, Retention, Cohorts',
    kind: 'data-project',
    rank: 5,
    targetMonth: 2,
    hours: 24,
    skills: ['Analytics', 'Metrics', 'Experimentation'],
    problem: 'A product loses most of its signups before they reach value, and nobody can say precisely where or why.',
    goal: 'Find the drop, quantify it, explain it, and recommend three interventions with expected effect sizes.',
    process: 'Question framing → funnel analysis → retention curve → cohort comparison → recommendations.',
    research: 'A public product dataset, analysed in SQL and in Amplitude.',
    discovery: 'The behaviour that separates retained users from churned ones in week one.',
    ux: 'Data presentation: every chart carries a sentence saying what to do about it.',
    metrics: 'Step conversion, D1/D7/D30 retention, cohort retention curves, and the retention plateau.',
    tradeoffs: 'Correlational, not causal, and the write-up says so. Honesty about that limit is itself the signal.',
    risks: 'Confusing correlation for cause. Mitigated by naming the experiment that would establish causality.',
    impact: 'Three sized recommendations, and the first public proof that you can do analytics.',
    lessons: '',
    why: 'Ranked #5, and scheduled earliest deliberately — it is the fastest route from Analytics 6.5 to visible evidence.',
  },
  {
    title: 'Product Strategy Memo — Should Company X Enter Market Y?',
    kind: 'strategy-doc',
    rank: 6,
    targetMonth: 9,
    hours: 28,
    skills: ['Product Strategy', 'Business Thinking', 'Communication'],
    problem: 'A company with a strong position in one market is considering an adjacent one, and the decision is being made on enthusiasm.',
    goal: 'A memo that reaches a clear recommendation with numbered assumptions, sized risks, and criteria that would prove it wrong.',
    process: 'Market sizing → competitive position → where we would win → what would have to be true → recommendation → kill criteria.',
    research: 'Public market data, competitor teardown, and stated assumptions where data is unavailable.',
    discovery: 'The one assumption the whole recommendation rests on.',
    ux: 'Document design: recommendation first, evidence second, appendix third.',
    metrics: 'Leading indicators for the first two quarters, and the number that would trigger a stop.',
    tradeoffs: 'Entering costs focus in the core market. The memo prices that rather than ignoring it.',
    risks: 'Market sizing built on assumptions that do not survive contact. Every one is numbered so it can be checked.',
    impact: 'A go/no-go recommendation a real executive could act on.',
    lessons: '',
    why: 'Ranked #6. The direct answer to the audit\'s strategy diagnosis: "should this company even build this?" rather than "how should this product evolve?"',
  },
  {
    title: 'Open Source Contribution',
    kind: 'open-source',
    rank: 7,
    targetMonth: 15,
    hours: 20,
    skills: ['Technical Depth', 'Leadership', 'UX'],
    problem: 'Your technical credibility and your collaboration style are both asserted rather than demonstrated.',
    goal: 'A merged contribution to a reputable project — documentation, UX improvement, or product planning.',
    process: 'Choose the project → find real friction → propose → contribute → get it merged.',
    research: 'Issue archaeology to find what maintainers actually want.',
    discovery: 'Where new contributors get stuck — usually the highest-value thing to fix.',
    ux: 'Documentation IA or an onboarding-flow improvement.',
    metrics: 'Merged PRs, and any measurable change in contributor onboarding.',
    tradeoffs: 'Documentation contributions merge faster than code; code contributions signal more. Do documentation first to build standing.',
    risks: 'Maintainer responsiveness is outside your control. Mitigate by picking an active project.',
    impact: 'Public, verifiable, timestamped evidence of collaboration on someone else\'s terms.',
    lessons: '',
    why: 'Ranked #7. The audit specifies documentation, UX improvements or product planning on a reputable project.',
  },
  {
    title: 'Enterprise Permissions Model — Case Study',
    kind: 'case-study',
    rank: 8,
    targetMonth: 6,
    hours: 26,
    skills: ['Systems Thinking', 'UX', 'Product Execution'],
    problem: 'Role-based permissions collapse when real organisations have matrix structures, delegation and temporary access.',
    goal: 'Design a permissions model that handles the real cases without becoming a configuration language.',
    process: 'Requirements from real org structures → model design → UI for granting and auditing → migration.',
    research: 'Five customer org charts and every permissions support ticket from a quarter.',
    discovery: 'Administrators do not want power, they want to be able to explain who can see what.',
    ux: 'Permission-granting flow, an effective-permissions viewer, and an audit trail.',
    metrics: 'Misconfiguration rate, time-to-provision a new user, and permission-related tickets.',
    tradeoffs: 'Chose a constrained role model with explicit delegation over full ABAC. Costs expressiveness; buys explicability.',
    risks: 'Under-serving the largest customers. Mitigated by an explicit escalation path rather than universal flexibility.',
    impact: 'Modelled: 50% reduction in permission misconfiguration incidents.',
    lessons: '',
    why: 'Case study #2 for Month 6. Permissions is named in the audit as part of your complex-enterprise-UX advantage — this makes it public.',
  },
]

export function buildPortfolio() {
  return PROJECTS.map((p, index) => {
    // Only the Month 2 analytics case study is in flight at seed time; the rest
    // are correctly scoped-but-unstarted, which is what month one looks like.
    const isActive = p.targetMonth === 2
    const completion = isActive ? 20 : 0

    return {
      id: id('pf', p.title),
      title: p.title,
      kind: p.kind,
      roiRank: p.rank,
      status: isActive ? 'in-progress' : 'not-started',
      completion,
      publishStatus: 'private',
      url: undefined,
      problem: p.problem,
      goal: p.goal,
      process: p.process,
      research: p.research,
      discovery: p.discovery,
      ux: p.ux,
      metrics: p.metrics,
      tradeoffs: p.tradeoffs,
      risks: p.risks,
      businessImpact: p.impact,
      lessons: p.lessons,
      // `why` is surfaced as the tooltip explaining the project's ROI rank.
      rationale: p.why,
      skillIds: p.skills.map((n) => S[n]).filter(Boolean),
      estimatedHours: p.hours,
      actualHours: isActive ? 5 : 0,
      targetDate: monthEnd(p.targetMonth),
      startedAt: isActive ? addDays(PROGRAMME_START, 26) : undefined,
      completedAt: undefined,
      attachments: [],
      screenshots: [],
      xp: p.hours * 15,
      order: index,
    }
  })
}

/* ------------------------------------------------------------- writing --- */

const WRITING = [
  {
    title: 'The Metric Tree I Wish I Had Built Two Years Ago',
    kind: 'article',
    month: 1,
    topics: ['Metrics', 'Enterprise SaaS'],
    skills: ['Metrics', 'Communication'],
    target: 1800,
    words: 640,
    status: 'drafting',
    outline:
      '1. The dashboard everyone ignored\n2. Why output metrics do not direct a team\n3. The chain: north star → inputs → leading → guardrails\n4. What changed when we rebuilt it\n5. The tree, in full',
  },
  {
    title: 'What a Public Dataset Told Me About Onboarding',
    kind: 'case-study',
    month: 2,
    topics: ['Analytics', 'Onboarding'],
    skills: ['Analytics', 'Metrics'],
    target: 2400,
    words: 0,
    status: 'outlining',
    outline: 'Funnel → the drop nobody looks at → retention split → three recommendations with sizes',
  },
  {
    title: 'Ten Experiments I Designed, and What Each Would Have Taught Us',
    kind: 'article',
    month: 3,
    topics: ['Experimentation'],
    skills: ['Experimentation'],
    target: 2200,
    words: 0,
    status: 'idea',
    outline: 'One section per plan: hypothesis, metric, MDE, what a null result would mean',
  },
  {
    title: 'Systems Over Features: Reading a Product\'s Data Model From the Outside',
    kind: 'teardown',
    month: 4,
    topics: ['Systems Thinking', 'Product Sense'],
    skills: ['Systems Thinking', 'Product Sense'],
    target: 2000,
    words: 0,
    status: 'idea',
    outline: 'Take Linear. Infer the schema from the UI. Show what the constraints buy.',
  },
  {
    title: 'How I Evaluated an LLM Feature Without Vibes',
    kind: 'article',
    month: 5,
    topics: ['AI Products', 'Evaluation'],
    skills: ['AI Product Knowledge', 'Metrics'],
    target: 2600,
    words: 0,
    status: 'idea',
    outline: '50 cases, four dimensions, one rubric. The adversarial cases that changed the design.',
  },
  {
    title: 'Redesigning a Ten-Year-Old Workflow',
    kind: 'case-study',
    month: 6,
    topics: ['Enterprise UX', 'Systems Thinking'],
    skills: ['UX', 'Systems Thinking'],
    target: 3200,
    words: 0,
    status: 'idea',
    outline: 'The exceptions that were the same exception. The path I chose not to support.',
  },
  {
    title: 'Permissions Are a Product, Not a Setting',
    kind: 'article',
    month: 7,
    topics: ['Enterprise UX', 'Complex Workflows'],
    skills: ['UX', 'Systems Thinking'],
    target: 2000,
    words: 0,
    status: 'idea',
    outline: 'Why RBAC breaks. What administrators actually want. The explicability principle.',
  },
  {
    title: 'The Architecture Decision That Was Actually a Product Decision',
    kind: 'article',
    month: 8,
    topics: ['Technical Depth', 'Systems Thinking'],
    skills: ['Technical Depth', 'Systems Thinking'],
    target: 2200,
    words: 0,
    status: 'idea',
    outline: 'Sync vs async, and how it determined what the product could promise users.',
  },
  {
    title: 'Pricing an AI Feature When Your Cost Floor Moves',
    kind: 'article',
    month: 9,
    topics: ['Pricing', 'AI Products'],
    skills: ['Business Thinking', 'AI Product Knowledge'],
    target: 2400,
    words: 0,
    status: 'idea',
    outline: 'Metering units customers understand. Margin at three volume tiers. What breaks at 100×.',
  },
  {
    title: 'Where Your Growth Loop Actually Leaks',
    kind: 'article',
    month: 10,
    topics: ['Growth', 'Analytics'],
    skills: ['Business Thinking', 'Analytics'],
    target: 2200,
    words: 0,
    status: 'idea',
    outline: 'Model the loop. Find the step with real leverage. Size three interventions.',
  },
  {
    title: 'What 25 Mock Interviews Taught Me About My Own Blind Spots',
    kind: 'essay',
    month: 11,
    topics: ['Interviewing', 'Career'],
    skills: ['Communication'],
    target: 1800,
    words: 0,
    status: 'idea',
    outline: 'The repeating criticism. The round I kept avoiding. What actually moved the scores.',
  },
  {
    title: 'Applying With Evidence Instead of Experience',
    kind: 'essay',
    month: 12,
    topics: ['Career', 'Portfolio'],
    skills: ['Communication', 'Business Thinking'],
    target: 2000,
    words: 0,
    status: 'idea',
    outline: 'Twelve months of artefacts. What recruiters responded to and what they ignored.',
  },
]

export function buildWriting() {
  return WRITING.map((w, index) => ({
    id: id('wr', w.title),
    title: w.title,
    kind: w.kind,
    status: w.status,
    words: w.words,
    targetWords: w.target,
    topics: w.topics,
    skillIds: w.skills.map((n) => S[n]).filter(Boolean),
    outline: w.outline,
    draft: '',
    publication: 'Personal site + LinkedIn',
    url: undefined,
    // The monthly article cadence: one per month for 24 months.
    scheduledFor: monthEnd(w.month),
    publishedAt: undefined,
    views: undefined,
    xp: 300,
    order: index,
  }))
}

export { addMonths }
